### ISSUE TITLE
Permission denied when calling sem_* functions on batch mode

### ISSUE THREAD

**Issue by diegohdk** [census-instrumentation/opencensus-php#266]
I don't know if this is the right place to create this issue, but I'm not being able to run the daemon to export the traces.

I have a Lavarel app with the following service provider:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use OpenCensus\Trace\Exporter\StackdriverExporter;
use OpenCensus\Trace\Integrations\Laravel;
use OpenCensus\Trace\Integrations\PDO;
use OpenCensus\Trace\Tracer;

class StackdriverServiceProvider extends ServiceProvider
{
    /**
     * @var StackdriverExporter
     */
    static $exporter = null;

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        self::$exporter = new StackdriverExporter([
            // infos about the project are set with env variables
            'async' => true,
            'debugOutput' => true,
            'batchOptions' => [
                'batchSize' => 5,
                'callPeriod' => 2.0,
                'workerNum' => 2
            ]
        ]);
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        if (php_sapi_name() == 'cli') {
            return;
        }

        Laravel::load();
        PDO::load();

        Tracer::start(self::$exporter);
        Tracer::inSpan(['name' => 'bootstrap', 'startTime' => LARAVEL_START], function () {});
    }
}
```

The app is running with no problems.

But when I execute the following command:

```sh
php /app/vendor/bin/google-cloud-batch daemon
```

The output is:

```
PHP Warning:  sem_get(): failed for key 0x4101159b: Permission denied in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 71
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\SysvConfigStorage->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:63
PHP   4. sem_get() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:71
PHP Warning:  sem_acquire() expects parameter 1 to be resource, bool given in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 81
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\BatchRunner->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:64
PHP   4. Google\Cloud\Core\Batch\BatchRunner->loadConfig() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:74
PHP   5. Google\Cloud\Core\Batch\SysvConfigStorage->lock() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:186
PHP   6. sem_acquire() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:81
PHP Warning:  shm_attach(): failed for key 0x4101159b: Permission denied in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 130
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\BatchRunner->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:64
PHP   4. Google\Cloud\Core\Batch\BatchRunner->loadConfig() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:74
PHP   5. Google\Cloud\Core\Batch\SysvConfigStorage->load() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:191
PHP   6. shm_attach() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:130
PHP Warning:  shm_attach(): failed for key 0x4101159b: Permission denied in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 156
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\BatchRunner->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:64
PHP   4. Google\Cloud\Core\Batch\BatchRunner->loadConfig() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:74
PHP   5. Google\Cloud\Core\Batch\SysvConfigStorage->clear() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:193
PHP   6. shm_attach() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:156
PHP Warning:  shm_remove_var() expects parameter 1 to be resource, bool given in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 157
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\BatchRunner->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:64
PHP   4. Google\Cloud\Core\Batch\BatchRunner->loadConfig() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:74
PHP   5. Google\Cloud\Core\Batch\SysvConfigStorage->clear() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:193
PHP   6. shm_remove_var() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:157
PHP Warning:  sem_release() expects parameter 1 to be resource, bool given in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 91
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchDaemon->__construct() /app/vendor/google/cloud-core/bin/google-cloud-batch:50
PHP   3. Google\Cloud\Core\Batch\BatchRunner->__construct() /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php:64
PHP   4. Google\Cloud\Core\Batch\BatchRunner->loadConfig() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:74
PHP   5. Google\Cloud\Core\Batch\SysvConfigStorage->unlock() /app/vendor/google/cloud-core/src/Batch/BatchRunner.php:196
PHP   6. sem_release() /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:91
PHP Fatal error:  Uncaught RuntimeException: Failed to attach to the shared memory in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php:132
Stack trace:
#0 /app/vendor/google/cloud-core/src/Batch/BatchRunner.php(191): Google\Cloud\Core\Batch\SysvConfigStorage->load()
#1 /app/vendor/google/cloud-core/src/Batch/BatchRunner.php(74): Google\Cloud\Core\Batch\BatchRunner->loadConfig()
#2 /app/vendor/google/cloud-core/src/Batch/BatchDaemon.php(64): Google\Cloud\Core\Batch\BatchRunner->__construct(Object(Google\Cloud\Core\Batch\SysvConfigStorage), Object(Google\Cloud\Core\Batch\SysvProcessor))
#3 /app/vendor/google/cloud-core/bin/google-cloud-batch(50): Google\Cloud\Core\Batch\BatchDaemon->__construct('/var/www/liket-...')
#4 {main}
  thrown in /app/vendor/google/cloud-core/src/Batch/SysvConfigStorage.php on line 132
```

If I run with the web server user:

```sh
sudo -u www-data php /app/vendor/bin/google-cloud-batch daemon
```

The output is:

```
PHP Warning:  file_get_contents(/tmp/Itemdc8wuE): failed to open stream: No such file or directory in /app/vendor/google/cloud-core/src/Batch/BatchJob.php on line 130
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchJob->run() /app/vendor/google/cloud-core/bin/google-cloud-batch:56
PHP   3. file_get_contents() /app/vendor/google/cloud-core/src/Batch/BatchJob.php:130
PHP Fatal error:  Uncaught Error: Call to a member function spans() on bool in /app/vendor/google/cloud-trace/src/TraceClient.php:146
Stack trace:
#0 [internal function]: Google\Cloud\Trace\TraceClient->insertBatch(Array)
#1 /app/vendor/google/cloud-core/src/Batch/BatchTrait.php(92): call_user_func_array(Array, Array)
#2 [internal function]: OpenCensus\Trace\Exporter\StackdriverExporter->send(Array)
#3 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(184): call_user_func_array(Array, Array)
#4 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(166): Google\Cloud\Core\Batch\BatchJob->callFunc(Array)
#5 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(147): Google\Cloud\Core\Batch\BatchJob->flush(Array)
#6 /app/vendor/google/cloud-core/bin/google-cloud-batch(56): Google\Cloud\Core\Batch\BatchJob->run()
#7 {main}
  thrown in /app/vendor/google/cloud-trace/src/TraceClient.php on line 146
PHP Warning:  file_get_contents(/tmp/ItemeP6ec1): failed to open stream: No such file or directory in /app/vendor/google/cloud-core/src/Batch/BatchJob.php on line 130
PHP Stack trace:
PHP   1. {main}() /app/vendor/google/cloud-core/bin/google-cloud-batch:0
PHP   2. Google\Cloud\Core\Batch\BatchJob->run() /app/vendor/google/cloud-core/bin/google-cloud-batch:56
PHP   3. file_get_contents() /app/vendor/google/cloud-core/src/Batch/BatchJob.php:130
PHP Fatal error:  Uncaught Error: Call to a member function spans() on bool in /app/vendor/google/cloud-trace/src/TraceClient.php:146
Stack trace:
#0 [internal function]: Google\Cloud\Trace\TraceClient->insertBatch(Array)
#1 /app/vendor/google/cloud-core/src/Batch/BatchTrait.php(92): call_user_func_array(Array, Array)
#2 [internal function]: OpenCensus\Trace\Exporter\StackdriverExporter->send(Array)
#3 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(184): call_user_func_array(Array, Array)
#4 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(166): Google\Cloud\Core\Batch\BatchJob->callFunc(Array)
#5 /app/vendor/google/cloud-core/src/Batch/BatchJob.php(147): Google\Cloud\Core\Batch\BatchJob->flush(Array)
#6 /app/vendor/google/cloud-core/bin/google-cloud-batch(56): Google\Cloud\Core\Batch\BatchJob->run()
#7 {main}
  thrown in /app/vendor/google/cloud-trace/src/TraceClient.php on line 146
```

Any idea?

**Comment by diegohdk** [comment]
After some debugging I found the problem.

At least for me the docs are not very clear about permissions, and the first thing is that the command `php /app/vendor/bin/google-cloud-batch daemon` must to be run with the HTTP server user, in my case `apache`. Otherwise it will not be able to access the shared memory. One workaround would be to set a wider permission for the semaphore, but I don't think this is a good idea.

That leads me to the next issue. For some reason my application is not being able to write in the system temp dir. Maybe is something related to SELinux blocking Apache to write there.

In the class `SysvProcessor` the method `submit` does the following:

```php
$tempFile = tempnam(sys_get_temp_dir(), 'Item');
$result = file_put_contents($tempFile, serialize($item));
```

That fails transparently, because it creates and writes to the file (aparently), but the file is not there. No errors nor warnings are generated. When I check with `ls -lha /tmp` there are no `Item*` files there.

My solution was to change the TMPDIR env variable inside my script to force the messages to be written in a different location, where Apache has access.

```php
// class StackdriverServiceProvider

/**
 * Register services.
 *
 * @return void
 */
public function register()
{
    putenv('TMPDIR=' . config('env.CLOUD_LOGS_TMPDIR'));

    self::$exporter = new StackdriverExporter([
        // infos about the project are set with env variables
        'async' => true
    ]);
}
```

Now the application is able to dump the traces into temp files, and the batch script can read them accordingly.

If this looks like a hack, please let me know the best way to solve it.
